version: "2"

services:
  rethink-db:
    container_name: "rethink-db"
    image: rethinkdb:latest
    ports: 
      - "28015:28015"
    volumes:
      - /go/data
 

  go-app:
    container_name: "go-app"
    image: golang:1.6.1-alpine
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-golang-glide
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: /bin/sh -c "cd src && glide install && go build && ./src"
    ports: 
      - "8000:8000"
    environment:
      - GOPATH=/go
 

