FROM golang

MAINTAINER Andre Dickinson <acdickin@gmail.com>

ENV GOBIN /go/bin

# build directories

RUN mkdir /go/src/app
ADD . /go/src/app
WORKDIR /go/src/app

# Go dep!
RUN go get -u github.com/golang/dep/... 
RUN dep init 
RUN dep ensure 